
package com.carrental.server;

import com.carrental.database.User;
import com.carrental.database.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.web.bind.annotation.*;

@SpringBootApplication
@RestController
public class Server {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public static void main(String[] args) {
        SpringApplication.run(Server.class, args);
    }

    @GetMapping("/hello")
    public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
        return String.format("Hello %s!", name);
    }

    @GetMapping("/main")
    public String main() {
        return String.format("This is the main page for the website. It will display cars available for rental " +
                "and provide tools for filtering.");
    }

    @PostMapping(path="/login")
    public @ResponseBody
    String addNewUser (@RequestParam String email, @RequestParam String passwordHash) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        User n = new User();
        n.setEmail(email);
        n.setPasswordHash(passwordHash);
        userRepository.save(n);
        return "Saved";
    }
}
