
package com.carrental.server;

import com.carrental.server.database.User;
import com.carrental.server.database.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

@SpringBootApplication
@RestController
public class Server {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

    public static void main(String[] args) {
        SpringApplication.run(Server.class, args);
    }

    @GetMapping("/hello")
    public String hello(@RequestParam(value = "name", defaultValue = "World") String name) {
        return String.format("Hello %s!", name);
    }

    @GetMapping("/main")
    public String main() {
        return String.format("This is the main page for the website. It will display cars available for rental " +
                "and provide tools for filtering.");
    }

    @PostMapping(path="/signup")
    public @ResponseBody
    String addNewUser(@RequestParam String email, @RequestParam String passwordHash) {
        // Check if email exists
        User user = userRepository.findByEmail(email);
        if (user != null) {
            return "User already exists.";
        }

        User n = new User();
        n.setEmail(email);
        n.setPasswordHash(passwordHash);
        userRepository.save(n);
        return "Saved";
    }

    @PostMapping(path="/login")
    public @ResponseBody
    ResponseEntity<String> checkUser(@RequestParam String email, @RequestParam String passwordHash) {
        // Check if email exists
        User user = userRepository.findByEmail(email);
        if (user != null) {
            return new ResponseEntity<String>("Found", HttpStatus.OK);
        }

        return new ResponseEntity<String>("Not Found", HttpStatus.NOT_FOUND);
    }
}
