version: '3.7'

services:
  mysql-development:
    image: mysql
    restart: always
    container_name: carrental_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=carrental
      - MYSQL_DATABASE=carrental
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./db_init:/docker-entrypoint-initdb.d:ro
    networks:
      - carrental

  carrental-server:
    build: server
    container_name: carrental_server
    # restart: always
    depends_on:
      - "mysql-development"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-development:3306/carrental?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: carrental
    networks:
      - carrental

  carrental-client:
    build:
      context: client
    container_name: carrental_client
    # logging:
    #   driver: "none"
    depends_on:
      - "carrental-server"
    ports:
      - "3000:3000"
    networks:
      - carrental
    command: npm start
    links:
      - carrental-server

networks:
  carrental:

volumes:
  db_data:
  db_init:
