version: '3.7'

services:
  mysql-development:
    image: mysql
    restart: always
    container_name: carrental_mysql
    environment:
      - MYSQL_ROOT_PASSWORD=carrental
      - MYSQL_DATABASE=carrental
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - ./db_data:/var/lib/mysql:rw
      - ./db_init:/docker-entrypoint-initdb.d:ro
    networks:
      - carrental
    deploy:
      placement:
        constraints: [node.role == manager]

  carrental-server:
    # build: 
    #   context: server
    image: eduardnicola/idp_project:latest-server
    container_name: carrental_server
    depends_on:
      - "mysql-development"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-development:3306/carrental?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: carrental
    networks:
      carrental:
        aliases:
          - server
    deploy:
      placement:
        constraints: [node.role == manager]

  carrental-client:
    # build:
    #   context: client
    image: eduardnicola/idp_project:latest-client
    container_name: carrental_client
    depends_on:
      - "carrental-server"
    ports:
      - "3000:3000"
    networks:
      - carrental
    command: npm start
    links:
      - carrental-server

  carrental-admin:
    # build: 
    #   context: admin
    image: eduardnicola/idp_project:latest-admin
    container_name: carrental_admin
    logging:
      driver: "none"
    depends_on:
      - "mysql-development"
    stdin_open: true
    tty: true
    ports:
      - "3005:3004"
    networks:
      - carrental

  prometheus:
    image: prom/prometheus:latest
    container_name: carrental_prometheus
    ports:
      - "9090:9090"
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - carrental
    

networks:
  carrental:

volumes:
  db_data:
  db_init:
  prometheus.yml:
